#ifndef USNWATCHER_H
#define USNWATCHER_H

#include "scanner.h"

#ifdef _WIN32

/* Rename pair: old_name → new_name (basenames), both in same directory */
typedef struct {
    char *old_name;
    char *new_name;
} RenamePair;

/* Rename group: all renames in one directory (parent path) */
typedef struct RenameGroup {
    char *parent_path;      /* directory containing renamed entries */
    RenamePair *pairs;
    int pair_count;
    struct RenameGroup *next;
} RenameGroup;

/* ---- lifecycle ---- */

/* Try to open the USN Journal for the volume containing `scan_path`.
 * Returns 1 on success, 0 if USN is unavailable. */
int usnwatcher_init(const char *scan_path);

/* Build initial FRN→path mapping from scanned tree (call after first scan). */
void usnwatcher_build_frn_map(Entry *root, const char *scan_path);

void usnwatcher_close(void);

/* ---- change detection ---- */

/* Read incremental USN records since last call.
 * Returns total number of changes, or 0 if no new records. */
int usnwatcher_read_changes(const char *scan_path, time_t now);

/* Skip past current USN — call after scanning to ignore records
 * generated by the scan itself (e.g. FILE_READ_ATTRIBUTES). */
void usnwatcher_skip_noise(void);

/* ---- change list (all types) ---- */

typedef struct {
    char *path;          /* relative path from scan root */
    int  change_type;    /* CHANGE_CREATED / _MODIFIED / _DELETED */
    char *rename_old;    /* old name if this is the NEW side of a rename, else NULL */
    char *rename_new;    /* new name if this is the OLD side of a rename, else NULL */
} UsnChange;

typedef struct {
    UsnChange *changes;
    int count;
} UsnChangeList;

/* Get all changes detected by USN since last read.
 * Caller must free with usnwatcher_free_changes(). */
UsnChangeList *usnwatcher_get_changes(void);
void usnwatcher_free_changes(UsnChangeList *list);

#endif /* _WIN32 */
#endif /* USNWATCHER_H */
